# These are supported funding model platforms

liberapay: neto737

custom:
  - 'https://www.paypal.com/donate/?business=T7RVRCXLZXB58&no_recurring=0&currency_code=USD'
  - 'https://www.blockchain.com/btc/address/bc1pduj90df9cs3md3gym3q809slfv2x5phnpv8xznajys5q3tlulnzqt3flwn'
  - 'https://etherscan.io/address/0xeef9220639F14E7A0FD825AAAd0574e5a8aD7A4B'
  - 'https://blockchair.com/litecoin/address/ltc1q508qfkd09vyya6c5zkfx4r248pf3ezj9ngjdr2'